// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7sKsF05Hx2J-1L4ZtF7LyUAm51ybJaR8',
    appId: '1:380509564475:web:c30949629b88757fb5b61e',
    messagingSenderId: '380509564475',
    projectId: 'ohanawebapp',
    authDomain: 'ohanawebapp.firebaseapp.com',
    storageBucket: 'ohanawebapp.appspot.com',
    measurementId: 'G-GYVGF3HFV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBauNouY5IP39HonLMpeJ_a-_W1ASGLJ4k',
    appId: '1:380509564475:android:c2919dfc0c719443b5b61e',
    messagingSenderId: '380509564475',
    projectId: 'ohanawebapp',
    storageBucket: 'ohanawebapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn_C47dr_Pp4XNGn53jJi7tngUuzKMkJA',
    appId: '1:380509564475:ios:3f78c8272d8a7fb3b5b61e',
    messagingSenderId: '380509564475',
    projectId: 'ohanawebapp',
    storageBucket: 'ohanawebapp.appspot.com',
    iosBundleId: 'com.example.ohanaWebPlateform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn_C47dr_Pp4XNGn53jJi7tngUuzKMkJA',
    appId: '1:380509564475:ios:3f78c8272d8a7fb3b5b61e',
    messagingSenderId: '380509564475',
    projectId: 'ohanawebapp',
    storageBucket: 'ohanawebapp.appspot.com',
    iosBundleId: 'com.example.ohanaWebPlateform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7sKsF05Hx2J-1L4ZtF7LyUAm51ybJaR8',
    appId: '1:380509564475:web:e215b552f8690461b5b61e',
    messagingSenderId: '380509564475',
    projectId: 'ohanawebapp',
    authDomain: 'ohanawebapp.firebaseapp.com',
    storageBucket: 'ohanawebapp.appspot.com',
    measurementId: 'G-9PTEHKVCRJ',
  );
}
